#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Please run with root privileges!"
    exit
fi

pushd $(dirname $0)

if [ $0 = "net" ]; then
    rm -rf ./*
    git clone https://github.com/b-mer/smart-linux-home-panel .
fi

source build.sh
cp bin/smart_home_panel /usr/bin

popd